"""delete testssss

Revision ID: c0f03da9bf56
Revises: b1234b732edb
Create Date: 2024-07-01 22:26:51.067041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f03da9bf56'
down_revision = 'b1234b732edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('test')
        batch_op.drop_column('test2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
